In [1]:
import numpy as np

In [2]:
marks = [
    [90, 93, 97],
    [99, 84, 89],
    [100, 98, 90]
]

In [6]:
n1 = np.array(marks)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 90  93  97]
 [ 99  84  89]
 [100  98  90]]
<class 'numpy.ndarray'>
2
(3, 3)


In [12]:
# indexing
print(n1[-1])
print(n1[-1][1]) # this way of doing in regular python is not optimal in numpy
print(n1[-1, 1]) # optimal way of doing row + column indexing in numpy

[100  98  90]
98
98


In [14]:
# slicing
# the marks scored by the last 2 students of the class
print(n1[-2:])

# the Physics, Chemistry marks scored by the last 2 students of the class
print(n1[-2:, :2])

[[ 99  84  89]
 [100  98  90]]
[[ 99  84]
 [100  98]]


In [16]:
# slicing + indexing
# the Physics, Maths marks scored by the first 2 students of the class
print(n1[:2, [0, -1]])

[[90 97]
 [99 89]]


In [17]:
print(n1)

[[ 90  93  97]
 [ 99  84  89]
 [100  98  90]]


In [18]:
# deduct 1 in physics from every student of the class
physics_deduct = n1 - [1, 0, 0]

In [19]:
print(physics_deduct)

[[89 93 97]
 [98 84 89]
 [99 98 90]]


In [21]:
# deduct 1 in physics, maths from the first and last student of the class
print(n1)
n5 = n1 - [
    [1],
    [0],
    [1]
]
print(n5)

[[ 90  93  97]
 [ 99  84  89]
 [100  98  90]]
[[89 92 96]
 [99 84 89]
 [99 97 89]]


In [26]:
#statistics
print(n1)
print(n1.sum(axis=1))
print(n1.mean(axis=0))

[[ 90  93  97]
 [ 99  84  89]
 [100  98  90]]
[280 272 288]
[96.33333333 91.66666667 92.        ]


In [27]:
m1 = np.array([
    [3, 4],
    [5, 2]
])
m2 = np.array([
    [1, 3],
    [6, 2]
])
print(m1)
print(m2)

[[3 4]
 [5 2]]
[[1 3]
 [6 2]]


In [31]:
print(m1 + m2)
print(m1 - m2)
print(m1 * m2) # this is not matrix multiplication
print(np.dot(m1, m2))

[[ 4  7]
 [11  4]]
[[ 2  1]
 [-1  0]]
[[ 3 12]
 [30  4]]
[[27 17]
 [17 19]]
