In [9]:
import numpy as np
import numpy.random as rd

In [6]:
print(np.zeros(10))
print(np.ones(20))
print(np.identity(3))
print(np.arange(11, 26))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [49]:
rd.randint(10)

3

In [77]:
rd.rand(3, 3)

array([[0.71497726, 0.94270882, 0.72221775],
       [0.68249438, 0.99225094, 0.99364096],
       [0.648167  , 0.12486285, 0.4198783 ]])

In [76]:
rd.randn(3, 3)

array([[-0.44970312, -0.55757585,  1.82486372],
       [ 0.92940885, -0.39354395, -0.53787954],
       [ 1.28810261,  0.48584484,  0.45605872]])

In [89]:
rd.binomial(10, 0.5, 1000)

array([ 6,  4,  3,  3,  6,  6,  5,  1,  6,  7,  3,  5,  7,  6,  4,  5,  7,
        5,  5,  4,  3,  5,  4,  3,  7,  3,  6,  8,  8,  5,  4,  6,  6,  3,
        4,  5,  5,  4,  4,  6,  7,  4,  6,  5,  4,  5,  3,  5,  6,  3,  2,
        3,  8,  1,  7,  6,  3,  8,  6,  9,  2,  2,  5,  6,  5,  3,  5,  5,
        4,  3,  4,  5,  3,  3,  2,  5,  4,  8,  5,  4,  6,  7,  7,  2,  5,
        4,  5,  4,  6,  6,  4,  2,  6,  3,  3,  6,  5,  4,  7,  7,  6,  4,
        6,  5,  4,  8,  8,  6,  5,  5,  4,  5,  5,  4, 10,  6,  2,  5,  4,
        5,  4,  4,  4,  6,  4,  5,  3,  5,  5,  2,  7,  7,  5,  5,  6,  6,
        3,  7,  8,  5,  5,  5,  6,  9,  8,  4,  7,  5,  4,  8,  4,  6,  7,
        6,  5,  3,  7,  3,  5,  6,  5,  7,  3,  3,  3,  7,  3,  6,  6,  7,
        4,  8,  3,  8,  5,  4,  5,  7,  7,  4,  3,  3,  7,  3,  7,  4,  4,
        2,  5,  8,  7,  6,  6,  6,  4,  4,  6,  4,  7,  5,  4,  7,  3,  4,
        6,  5,  3,  2,  7,  3,  7,  5,  5,  7,  3,  0,  5,  4,  5,  4,  5,
        5,  5,  4,  5,  4