In [2]:
print('Hello World')

Hello World


In [4]:
for v in range(0, 21, 2):
    print(v)

0
2
4
6
8
10
12
14
16
18
20


In [6]:
import numpy as np

In [7]:
marks = [10, 1, 10, 3, 4, 5, 10, 6, 7, 4, 5, 8, 2]

In [13]:
# ndarray
n1 = np.array(marks, dtype=np.int8)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

[10  1 10  3  4  5 10  6  7  4  5  8  2]
<class 'numpy.ndarray'>
1
(13,)
int8


In [18]:
# indexing
print(n1[0])
print(n1[1])
print(n1[-1])
print(n1[-3])

# multiple indexing
print(n1[[0, -1]])

10
1
2
5
[10  2]


In [20]:
# indexing + modify
n1[-1] = 4
print(n1)

n1[[0, -1]] = 0 # broadcast 0 to the 2 indexes
print(n1)

[10  1 10  3  4  5 10  6  7  4  5  8  4]
[ 0  1 10  3  4  5 10  6  7  4  5  8  0]


In [25]:
# slicing
print(n1)
print(n1[0:3])
print(n1[-4:])
print(n1[:4])

[ 0  1 10  3  4  5 10  6  7  4  5  8  0]
[ 0  1 10]
[4 5 8 0]
[ 0  1 10  3]


In [27]:
# slicing + modification
n1[2:5] = 0 # broadcasting
print(n1)

[ 0  1  0  0  0  5 10  6  7  4  5  8  0]


In [28]:
# arithmetic operations
n2 = np.array(marks, dtype=np.int8)
print(n2)

[10  1 10  3  4  5 10  6  7  4  5  8  2]


In [29]:
n3 = n2 - 1
print(n3)

[9 0 9 2 3 4 9 5 6 3 4 7 1]


In [33]:
# relational operations
print(n2)
print(n2 > 5)
print((n2 == 10) | (n2 < 2))

[10  1 10  3  4  5 10  6  7  4  5  8  2]
[ True False  True False False False  True  True  True False False  True
 False]
[ True  True  True False False False  True False False False False False
 False]


In [37]:
# filtering
print(n2)
# filter out all students who scored more than 5 marks
n4 = n2[n2 > 5]
print(n4)

# filter out all students who scored 10 marks or less than 2
n5 = n2[(n2 == 10) | (n2 < 2)]
print(n5)

[10  1 10  3  4  5 10  6  7  4  5  8  2]
[10 10 10  6  7  8]
[10  1 10 10]


In [45]:
# mathematics
print(n2)
print(n2.min())
print(n2.max())
print(n2.mean())
print(np.median(n2))
print(n2.std())
print(n2.var())

[10  1 10  3  4  5 10  6  7  4  5  8  2]
1
10
5.769230769230769
5.0
2.9392266422373536
8.639053254437869


In [47]:
print(n2.cumsum())
print(n2.cumprod())

[10 11 21 24 28 33 43 49 56 60 65 73 75]
[       10        10       100       300      1200      6000     60000
    360000   2520000  10080000  50400000 403200000 806400000]


In [50]:
print(n2)
n2.sort()

[ 1  2  3  4  4  5  5  6  7  8 10 10 10]


In [51]:
print(n2)

[ 1  2  3  4  4  5  5  6  7  8 10 10 10]


In [53]:
print(np.unique(n2))

[ 1  2  3  4  5  6  7  8 10]


In [56]:
n3 = np.array(marks, dtype=np.int8)
print(n3)

[10  1 10  3  4  5 10  6  7  4  5  8  2]


In [58]:
n4 = np.where(n3 > 5, 1, 0)
print(n4)

[1 0 1 0 0 0 1 1 1 0 0 1 0]
